version: '3.1'

services:
  voteframe:
    env_file:
      - .env
    build:
      context: ./
      args: 
        - APP_URL=${VOCDONI_SERVER}
    ports:
      - ${VOCDONI_LISTENPORT}:${VOCDONI_LISTENPORT}
    sysctls:
      net.core.somaxconn: 8128
    volumes:
      - voteframe:/app/data
    restart: ${RESTART:-unless-stopped}

volumes:
  voteframe: {}
